FROM bellsoft/liberica-openjdk-alpine:11.0.16.1-1
COPY ./ ./src
RUN javac -sourcepath ./src -d ./out ./src/main/lesson1/java/Main.java
RUN java -classpath ./out main.Main
RUN javadoc -d ./doc -sourcepath ./src -cp ./out -subpackages lesson1 main
